package com.base.models;
// Generated 15.2.2016 12:23:53 by Hibernate Tools 4.3.1



/**
 * RelTable generated by hbm2java
 */
public class RelTable  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Student student;
     private Teacher teacher;

    public RelTable() {
    }

    public RelTable(Course course, Student student, Teacher teacher) {
       this.course = course;
       this.student = student;
       this.teacher = teacher;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }




}


